# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biosignal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'biosignal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62iosignal.proto\x12\tbiosignal\"X\n\rSignalRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x10\n\x08is_burst\x18\x03 \x01(\x08\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\":\n\x0eSignalResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x18\n\x10trigger_training\x18\x02 \x01(\x08\x32R\n\rBioNetService\x12\x41\n\nSendSignal\x12\x18.biosignal.SignalRequest\x1a\x19.biosignal.SignalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biosignal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQUEST']._serialized_start=30
  _globals['_SIGNALREQUEST']._serialized_end=118
  _globals['_SIGNALRESPONSE']._serialized_start=120
  _globals['_SIGNALRESPONSE']._serialized_end=178
  _globals['_BIONETSERVICE']._serialized_start=180
  _globals['_BIONETSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
