# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/biosignal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/biosignal.proto\x12\tbiosignal\"X\n\rSignalRequest\x12\x13\n\x0bhospital_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x10\n\x08is_burst\x18\x03 \x01(\x08\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\":\n\x0eSignalResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x18\n\x10trigger_training\x18\x02 \x01(\x08\x32X\n\rBioNetService\x12G\n\x0cStreamSignal\x12\x18.biosignal.SignalRequest\x1a\x19.biosignal.SignalResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.biosignal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIGNALREQUEST']._serialized_start=37
  _globals['_SIGNALREQUEST']._serialized_end=125
  _globals['_SIGNALRESPONSE']._serialized_start=127
  _globals['_SIGNALRESPONSE']._serialized_end=185
  _globals['_BIONETSERVICE']._serialized_start=187
  _globals['_BIONETSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
