# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import biosignal_pb2 as protos_dot_biosignal__pb2


class BioNetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSignal = channel.stream_stream(
                '/biosignal.BioNetService/StreamSignal',
                request_serializer=protos_dot_biosignal__pb2.SignalRequest.SerializeToString,
                response_deserializer=protos_dot_biosignal__pb2.SignalResponse.FromString,
                )


class BioNetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamSignal(self, request_iterator, context):
        """UPGRADE: Unary → Bidirectional Streaming
        One persistent HTTP/2 stream replaces thousands of TCP handshakes
        during a seizure burst. The server can now push back control signals
        (e.g. trigger_training=True) without the client polling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BioNetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSignal': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSignal,
                    request_deserializer=protos_dot_biosignal__pb2.SignalRequest.FromString,
                    response_serializer=protos_dot_biosignal__pb2.SignalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biosignal.BioNetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BioNetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamSignal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/biosignal.BioNetService/StreamSignal',
            protos_dot_biosignal__pb2.SignalRequest.SerializeToString,
            protos_dot_biosignal__pb2.SignalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
